---
title: The good, the bad, and the ugly
author: ~
date: '2020-09-10'
slug: extinction
categories: []
tags: []
subtitle: ''
summary: 'We are not as good as we may think!'
authors: []
lastmod: '2020-09-10T00:31:29+01:00'
featured: no
image:
  caption: 'Harvey Dent using a coing to decide on the fate of the bartender'
  focal_point: ''
  preview_only: no
projects: []
---



Yesterday, I started showing my friends this blog. And they really loved what I've been writing and noticed a development since my first published post. I am grateful for your kind words, it means a lot for me to hear your constructive comments and encouragements. This means that this blog is serving its purpose, learning to write, organizing thoughts and developing interesting ideas.

I asked few friends what they think I should write about next. I would say the answers converged into one topic, how can humanity save itself.? I think this subject is really beyond the scope of this humble blog. I am neither a philosopher nor equipped with enough knowledge to answer such a question or write about it. But I maybe have few things to say about the question itself. 

First let me start by saying that this question is my personal aggregation of what I have been asked to write about, I might be wrong, but its my blog, sue me.

Second, Human history was basically a series of wars, crimes, slavery, treason, and political plots. Even our modern life revolves around the same typical "rituals" of this race. In fact with technological advancement, these rituals simply took new forms, especially knowledge wise and economically, but in a more sophisticated (politically correct) manner, and also in a more destructive manner. But this is a subject for another time.

Saving the human race from itself is basically assuming that the nature of the human being is good, and that good humans cannot become bad. Therefore all we need to do is end what incites the human race to do these cruelties and we will be all right, "Harvey Dent" the DA who turned evil in "Batman Arkham city" is the perfect answer to this statement. Simply put, humans are assholes by construction, those who watched 'The walking dead' will relate instantly("fight the dead fear the living", right?). Good and evil are relative terms, and we cannot simply bi-define each individual of the entire human race. In this context the voluntary human extinction movement arises, it supports the human extinction as it views the human race as the major factor of environmental degradation and calls for individuals to halt the breeding process in order to gradually cause the decrease in the world population and cause the extinction of the race. 

Though all these statements are debatable to some extent, the fact that humans are calling for their race to be eradicated by one mean or another, is a major lead on the self-destructing nature of humanity. Therefore, asking for a way to save it is quite selfish, In fact it reflects a sense of privilege and guilt. How much comfort does one have to have in order to be shielded from the horrors of life? Consequently, the question is not about saving the humanity from itself, that's a matter left to the dynamics of natural selection, but rather how can humanity live with minimal pain and suffering. Eventually, the only thing we can change is how we perceive the world, not the world itself.

Thank you for stopping by.