---
title: Six months earlier
date: 2022-09-01T15:51:48+01:00
draft: true
---


At the time of writing these words I was spending my last few hours in the REACH office in Tunis, closing almost 4 months of what I may call a very interesting, challenging and international experience. This is an appreciation post to the short yet wonderful experience I had at REACH and a continuation to what I described in the previous blog post. 


After leaving National Pen, I had to start over, question everything, and simply reflect on what I went through. The idea was to sell all the skills and experience I have, and use that to get a new job that might help me find meaning in my life(not that I don't have any, but it kinda help to have a job you like to wake up to every morning). My job hunting journey was difficult and the path there was very rocky. 

One month in I had a local company offering me a job as a BI analyst, while at the same time having another unofficial offer as an R consultant with the WHO Afro. I decided to go with the latter until they emailed me that they changed their minds for some reason and won't proceed with an official offer even after I integrated their official communication channels. Basically I turned down an official offer for a non official one, waited for the best, but the best never happened at that point. You can imagine the heavy toll of such a severe disappointment on me adding to my already fragile mental state at that time, TLDR; it wasn't good. 

Eventually I had to move on and continue in my objective: landing a job that brings meaning to my life, a job that challenges me technically and that I can harness experience from doing it everyday. 

Till that point, I couldn't really tell how far or close I was to my objective, it was unclear to me how good or bad I was doing. I conducted countless interviews and technical tests but the response is usually the same, either *"None"*, or an email starting with *"we regret"*. The latter response was rarely transmitted to me though. Tunisian recruiters usually(except some rare examples as I said) never inform me of the fate of my application, I cannot fathom the idea that a professional recruiter would behave in such a rude and demeaning manner, it's simply disgusting.

Every day I woke up, I had to come up with new idea, I had to think on how to improve some projects, and make new ones. Every day I needed to reflect on the previous days, and figure out what went wrong or right. Every day, as confused and frustrated and maybe even depressed as I was I had to go forward. Moving forward got me to the point where I had 2 great offers at the same day, it was an amazing feeling, the biggest dopamine rush I've ever had in my life. I decided to go with REACH's offer, and the rest was history. 













