---
title: Normal_people
date: 2022-09-30T10:34:44+02:00
draft: true
---


When the dark cold nights of Pécs hits your bones, you lay in your bed wearing a thousand layers of cloth and you start scrolling through your youtube home page untill you fall asleep. This time, youtube didn't help get sleep, this time I went through an existantional roller coster that kept me awake for way past my bed time. 

You can check the video here, shout out to *Freedom in Thought* channel for it's great content.

<iframe width="560" height="315" src="https://www.youtube.com/embed/IXZFHYS1eV4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


Basically the author stated that self-discipline is a social ideal that enslaves your authentic self and ideals defining self-discipline as **"doing something you don't really want to do"**. Thought I don't totally disagree with the writer, this is not what kept me awake, rather the realisation that I'm not sure about my authentic self, or at least how authentic myself is. And since my entire rehtereic is based on authenticity, I felt really bad that I couldn't answer that question, worse when I realised that I might not have a single idea of my own nor a system of ideals and values. That hurts like bitch. 

However despite my realisation and the low feeling I had at that time, I had some reservations regarding the framework used by the author to define and scope self-discipline it's not complete and rather shallow. It's not just *"doing something you don't really want to do"*, rather it's about tolerating immediate suffering in the present for a greater reward in the future. It might however be true that the desired reward or the objective of the discipline might be the result of social pressure. But this doesn't mean that being self-disciplined is non-authentic or a form of social slavery in absolute terms. 

I had to ask myself more questions than I thought the video would help me answer after watching it. The author tried to give some answers, but they merely scratched the surface of the deep the questions it raised.

what is the authentic self? The author stated it's a self that's free from social pressure and expectation. 


supressing authenticity 

being out of touch with one-self true feelings and desires

forcing yourself to do things you don't want to do is not self -discipline it's slavery

sacrificing authenticity for society ideals

self discipline is being a disciple for one self, understand their feelings while discovering their own ideals 



This also doesn't mean that the social effects on your ideals are not significant, to the contrary, they most likely are the most significant. But the question is how do we know what parts of us are authentic and what parts of us are not, is it okay to not be entirely authentic psychologically at least? If striving for authenticity is very important isn't *striving* another side of the self-discipline coin.?

