---
title: "New capital, old ideas"
subtitle: ""
summary: "Between the overwhelming nature of the labor market and my future beyond the herd."
authors: []
tags: []
categories: []
date: 2020-09-11T14:55:22+01:00
lastmod: 2020-09-11T14:55:22+01:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: "Carl Marx, and Adam Smith: the battle goes on"
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

For some time, I have been thinking about what should I write about next and frankly I couldn't come up with an interesting subject. At that point I started thinking about how am I going to face the labor market when I finish my miserable thesis. Instead, being the procrastinator that I am, I created a [fieverr account](https://www.fiverr.com/share/lvd1ry) so I can provide my services and help people on an international level(also to give the anxious monkey inside my head a reason to stfu). To make this happen I realized that I needed to upgrade my networking game on twitter and linkedIn. However, while I was trying to figure this mess up, the figure of "Azzen Abidi" crossed my mind. In fact, Azzen inspired me to start writing, but I never did, until I was facing the inevitable misery of my thesis. This is a shout out to Azzen, may he get back to share his writing with us again.

Azzen's absence in medium, did not prevent me from thinking about my next job, my independence and financial stability, and more importantly about my skill set and the things I need to learn to simply not survive, but rather, live. Going from not caring at all, to being 100% responsible for your life is an overwhelming idea, especially when the basic axis behind it is financial stability. Nevertheless, In a country characterized by a deformed labor market, a structurally paralyzed economy, and in the context of world wide recession, financial stability is out of reach.

Financial stability is usually related to having a job, which means being a slave to an entity for some wage in order to be able to survive. However, surviving will be such a burden for anyone, that they will barely be able to invest themselves in what actually can produce wealth : Knowledge and Skill. Therefore, with my utter refusal to become a wage boomer, being self employed arises as a possible alternative. However this approach, requires an initial investment, or rather, some sort of a comfortable financial situation that allows me to orient the necessary time and energy to the knowledge and skill in question. Hence, the universal basic income. 

The brave idea behind the universal basic income, is that it is an opposite representation to the wage system. In one hand, the wage system starts by draining you from time and skill in return to a remuneration that will barely allows you to survive rather than live. While in the other hand the universal basic income starts by given you the financial means necessary to be active and hopefully invest your time and skill to create even more wealth for the collective welfare. However, the intriguing point is not about whether a basic income is fair or not, but rather, how universal should it be?

In summary, escaping the wage system, and the social prison that it represents is an overwhelming idea in spite of the obvious factors that makes it almost obsolete in our time. Those factors are mainly related to the intense globalization, the technological advancement, and the open access to knowledge and skill. In my case, this is overwhelming to realize, because the hardest part is to start, and frankly who knows if I really have to what it takes to actually make it without the herd. 

Thank you for stopping by.