---
title: To sabotage, or not to sabotage!
summary: "Greatful, thankful, and proud for the past. Excited, alert and hopeful for the future!"
date: 2021-12-29T22:40:31+01:00
draft: false
image:
  caption: "At the front, George Cochran Lambdin-1866"
  focal_point: ""
  preview_only: false
---

On the 23rd of December, National Pen the company I work at, prepares all staff everywhere in the world to go on an annual leave. It seems there's a tradition to play *secret Santa* on that day, a game to which I was unfamiliar, I frankly didn't know what to expect. The rules were simple, everyone randomly picks a name that they should keep secret and to whom they need to give a present without overspending a budget that everyone agrees on. I found the idea brilliant, and wished I was exposed to such acts of kindness when I was a kid. 

The sight of what my team mates did on the 4 of June for me was unforgettable. A month before, on may the 4th I celebrated my birthday, but since we were working from home in different locations at that time we couldn't meet. So a month later when we got back to the office, they surprised me with a late Birthday cake(which was super good, GOD!), and boy did they made my day, and probably my year.

2021 was hard on many people, I sympathize with anyone who went through hard times and acknowledge how fortunate I was to not live through any of those hardships. Indeed I'm *grateful* for all what 2021 had for me. Last year I told myself that I needed to become a *nicer person*. Usually I'm not, as I seek dominance through conflict and argue to respond rather than to listen and understand. I will not say that this was 100% eliminated this year, but definitely reduced to a noticeable degree according to close friends and family. This positive change and development wouldn't have been possible if I wasn't working with the team I currently belong to, I am forever grateful to them, I love them all. 

I can't be writing this article without mentioning one of the most intense experiences I've ever had. I've never had the opportunity to go on and camp in nature until this year, when a friend of mine suggested to me to go on an adventure, and so we did. We got lost and didn't know where to go, we climbed the same mountain twice looking for the camping site, and then a third time to enjoy the view, got attacked by a pack of wild pigs, made new friends, and enjoyed a hot spring. All of that in 24 hours. I should camp more in order to escape the mediocrity and the stress of my daily routine.

Order is hard to establish, and sticking to it is even harder, but this year, I was capable of establishing a new habit and hitting the gym regularly. In fact lifting weights was a great help in fighting the darkness inside me, to start feeling better, looking better, and thinking better. This simple act of moving weights around changed so much in so little time I can't imagine what would I be writing have I not started. The gym was probably the missing piece I needed to get my shit together.

Yesterday a year ago, I defended my thesis with honors, a month later I started in my current position at National Pen. 6 months afterwards I started looking for other opportunities and applying to positions where I can put to use my analytical edge. I was unfortunate for countless times to say the least, to the point that doubt overtook my thoughts and I started to loose my confidence and my motivation to go forward. Though each time I prepare an application where I'm a favorable candidate, I keep telling my self to lower my expectations and to simply control the emotional attachment to the potential change that might happen if selected. Despite all of that, the rejection email is always hard to read and digest. Harder it is when I have no explanation of why I was not selected. 

Looking back at what went wrong this year, namely being rejected from everything, I don't feel bad that it happened, rather I feel bad for not doing more to guarantee the candidacies, it was not just bad luck. I should have worked so hard to be the luckiest person in any of the application processes. But I don't, it's like a shadow version of myself protesting against me for applying and trying to go forward. I went through great positive changes, character wise and habit wise, now it's time to use those changes in order to directly impact my professional and personal life. *Next year, should be the year I stop sabotaging myself and out work the competition.*


Cheers and happy new year!


