---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Facing time: the consquences"
subtitle: ""
summary: "Standing in the face of infinity, with nothing but genetic evolution!"
authors: []
tags: []
categories: []
date: 2020-09-25T11:21:10+01:00
lastmod: 2020-09-25T11:21:10+01:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: "An olive tree is a symbol of time-resistance, able to live for thousands of years"
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

Last Tuesday, my grandmother died after 2 years of fighting liver failure, dementia, and hyper anxiety. May she rest in peace, and may god have mercy upon her. She basically raised me, and was my shield every time I did something stupid, and when nobody tolerated me in my teenage years, she did. I am relived that she finally rested, it was hard seeing her going through all of that. None could have done anything. These past couple of days has reminded me that death is inevitable, no matter who we are or how much we are worth, we will end up buried in dirt. 

I wasn't going to write anything about this, but today I couldn't advance at all in my thesis work, I basically spend the day looking for opportunities past the master's, and somehow I managed to stress over everything around me with out any reason. It was just weird. 

Today, when I was looking for research openings in Germany, the US, and France, I was very anxious realizing that maybe I don't have what it takes to be a researcher. After all these years I am yet to develop that reflex on analysis or code. And while this is true for some part, I think its just a way for the anxious monkey in my brain to stay worried, because at the end no matter what amount of knowledge I have at a given point its never enough to get to the next level of mastery. I should keep doing what I have always done, pursuing knowledge, reading, writing, and coding everyday. 

Perseverance beats talent. consistency beats intelligence, and self awareness beats recognition from others.

The results of the years I spent nerding my way through every subject are not lost, I am not seeing them because at each step I upgrade my skills and awareness I go on to the next challenge. Yes I am lazy, that's why I sacrificed my social contacts with my family and friends to be able to actually do this. 

Now, even though I have fostered a very useful set of tools and skills in the previous years, which were backed up by the research curse that I've got this year, my work is yet far from being over. I need not to rest, I need not to quit, I need not to compare myself neither with my peers neither with myself at different moments in my life. Rather I need to focus on the present moment, the opportunities that the "now" got for me. And the "now" is no other than my thesis, the longest document I have written, and the best thing that ever happened to me.

You are close, Hsin, hang in there.

