---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Le moi en marche!"
subtitle: ""
summary: "A lookback to my thesis defense and some thoughts and feelings about that day that I wanted to share."
authors: []
tags: []
categories: []
date: 2020-12-28T22:20:36+01:00
lastmod: 2020-12-28T22:20:36+01:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: "Mission Accomplished -Geno Peoples"
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

Friday, the 25th of December, I defended my master thesis entitled : "A Directional Distance Function Double-Bootstrap Approach to Assess the Tunisian Education System". Now that I got the chance to think about what I went through and how I felt, I decided to share some thoughts.

## Mission accmpished

The Tunisian higher education system is simply bankrupt, that's how I can describe the situation of our universities and institutions. It's basically the context of the entire country. My mission when I started working on my thesis was to find a way to implicitly defy this context in order to set my self apart from a bankrupt system, which was accomplished through my thesis.

## Smooth operator

My presentation was supposed to be held in the afternoon, I don't live in Tunis where the school is so I had to commute there early in the morning to avoid any surprises. I got there and started preparing for my presentation as I didn't finish all the slides, I didn't prepare as much as I really wanted, but It was enough and everything went really smoothly during the presentation and the Q&A. The only downside, is that my sister didn't take any good pictures of me while unpacking my presentation skills. Merde!

## Blessed inedeed

I am blessed and grateful for the journey that I had. I am blessed indeed that I was associated with my supervisor, and very fortunate for the family that brought me to this world, and supported me each and every step of the way. I think my new year resolution should be about treating my family and friends better and more fairly. In a nutshell, my next mission should be to be less of a dick than I can sometimes be. 

## A brief moment of peace 

When everything was done, I walked out of the school into the car and I threw myself into the front seat and just breath for few seconds, then told my father: "Let's go home". This moment was probably the most important moment of my life that I can think of. It felt utterly peaceful. To this hour, I still don't think I have fulfilled my self in any way through this master, but it was nice to breath for few seconds without any burden, deadlines, or something that needs to be done. I am saying few seconds, because that's how much time it took me to actually realize I needed to think about my next step. 

## Next step: Forward!

Imagine yourself in battlefield, you prevailed and won. But you got no command center for detailed instruction. Basically in such a case, soldiers will turn to the highest ranking officer in the group and ask him to take charge and provide them with orders. That officer was me after the brief moment of peace that I had. Unfortunately the soldiers are also a copy of me. And the officer me had no orders to give at that time. The only think that he could think of was to write this, and just move forward.

Thank you for stopping by.








